
export const TOPIC_MAPPING: Record<string, string[]> = {
  "1": ["Array", "Hash Table"],
  "2": ["Linked List", "Math"],
  "3": ["Hash Table", "String", "Sliding Window"],
  "4": ["Array", "Binary Search", "Divide and Conquer"],
  "5": ["String", "Dynamic Programming"],
  "11": ["Array", "Two Pointers"],
  "15": ["Array", "Two Pointers", "Sorting"],
  "19": ["Linked List", "Two Pointers"],
  "20": ["String", "Stack"],
  "21": ["Linked List", "Recursion"],
  "22": ["String", "Backtracking"],
  "23": ["Linked List", "Divide and Conquer", "Heap (Priority Queue)"],
  "31": ["Array", "Two Pointers"],
  "33": ["Array", "Binary Search"],
  "39": ["Array", "Backtracking"],
  "42": ["Array", "Two Pointers", "Stack", "Monotonic Stack"],
  "46": ["Array", "Backtracking"],
  "48": ["Array", "Math", "Matrix"],
  "53": ["Array", "Divide and Conquer", "Dynamic Programming"],
  "54": ["Array", "Matrix", "Simulation"],
  "55": ["Array", "Greedy", "Dynamic Programming"],
  "56": ["Array", "Sorting"],
  "62": ["Math", "Dynamic Programming", "Combinatorics"],
  "70": ["Math", "Dynamic Programming", "Memoization"],
  "72": ["String", "Dynamic Programming"],
  "75": ["Array", "Two Pointers", "Sorting"],
  "76": ["Hash Table", "String", "Sliding Window"],
  "78": ["Array", "Backtracking", "Bit Manipulation"],
  "79": ["Array", "Backtracking", "Matrix"],
  "94": ["Stack", "Tree", "Depth-First Search", "Binary Tree"],
  "98": ["Tree", "Depth-First Search", "Binary Search Tree", "Binary Tree"],
  "101": ["Tree", "Depth-First Search", "Breadth-First Search", "Binary Tree"],
  "102": ["Tree", "Breadth-First Search", "Binary Tree"],
  "104": ["Tree", "Depth-First Search", "Breadth-First Search", "Binary Tree"],
  "105": ["Array", "Hash Table", "Divide and Conquer", "Tree", "Binary Tree"],
  "121": ["Array", "Dynamic Programming"],
  "124": ["Tree", "Depth-First Search", "Binary Tree"],
  "128": ["Array", "Hash Table", "Union Find"],
  "136": ["Array", "Bit Manipulation"],
  "138": ["Hash Table", "Linked List"],
  "139": ["Hash Table", "String", "Dynamic Programming", "Trie", "Memoization"],
  "141": ["Hash Table", "Linked List", "Two Pointers"],
  "146": ["Hash Table", "Linked List", "Design", "Doubly-Linked List"],
  "152": ["Array", "Dynamic Programming"],
  "153": ["Array", "Binary Search"],
  "155": ["Stack", "Design"],
  "160": ["Hash Table", "Linked List", "Two Pointers"],
  "169": ["Array", "Hash Table", "Divide and Conquer", "Sorting", "Counting"],
  "198": ["Array", "Dynamic Programming"],
  "199": ["Tree", "Depth-First Search", "Breadth-First Search", "Binary Tree"],
  "200": ["Array", "Depth-First Search", "Breadth-First Search", "Union Find", "Matrix"],
  "206": ["Linked List", "Recursion"],
  "207": ["Graph", "Topological Sort", "Breadth-First Search", "Depth-First Search"],
  "208": ["Hash Table", "String", "Design", "Trie"],
  "215": ["Array", "Divide and Conquer", "Sorting", "Heap (Priority Queue)", "Quickselect"],
  "226": ["Tree", "Depth-First Search", "Breadth-First Search", "Binary Tree"],
  "230": ["Tree", "Depth-First Search", "Binary Search Tree", "Binary Tree"],
  "234": ["Linked List", "Two Pointers", "Stack", "Recursion"],
  "236": ["Tree", "Depth-First Search", "Binary Tree"],
  "238": ["Array", "Prefix Sum"],
  "239": ["Array", "Sliding Window", "Deque", "Heap (Priority Queue)", "Monotonic Queue"],
  "240": ["Array", "Binary Search", "Divide and Conquer", "Matrix"],
  "283": ["Array", "Two Pointers"],
  "287": ["Array", "Two Pointers", "Binary Search", "Bit Manipulation"],
  "295": ["Two Heaps", "Design", "Heap (Priority Queue)", "Data Stream"],
  "297": ["Tree", "Depth-First Search", "Breadth-First Search", "Design", "Binary Tree"],
  "300": ["Array", "Binary Search", "Dynamic Programming"],
  "322": ["Array", "Dynamic Programming", "Breadth-First Search"],
  "344": ["Two Pointers", "String"],
  "347": ["Array", "Hash Table", "Divide and Conquer", "Sorting", "Heap (Priority Queue)", "Bucket Sort", "Quickselect"],
  "394": ["String", "Stack", "Recursion"],
  "416": ["Array", "Dynamic Programming"],
  "437": ["Tree", "Depth-First Search", "Binary Tree"],
  "438": ["Hash Table", "String", "Sliding Window"],
  "448": ["Array", "Hash Table"],
  "494": ["Array", "Dynamic Programming", "Backtracking"],
  "543": ["Tree", "Depth-First Search", "Binary Tree"],
  "560": ["Array", "Hash Table", "Prefix Sum"],
  "567": ["Hash Table", "Two Pointers", "String", "Sliding Window"],
  "581": ["Array", "Two Pointers", "Stack", "Greedy", "Sorting", "Monotonic Stack"],
  "617": ["Tree", "Depth-First Search", "Breadth-First Search", "Binary Tree"],
  "621": ["Array", "Hash Table", "Greedy", "Sorting", "Heap (Priority Queue)", "Counting"],
  "647": ["String", "Dynamic Programming"],
  "704": ["Array", "Binary Search"],
  "739": ["Array", "Stack", "Monotonic Stack"],
  "763": ["Hash Table", "Two Pointers", "String", "Greedy"],
  "785": ["Graph", "Depth-First Search", "Breadth-First Search", "Union Find"],
  "876": ["Linked List", "Two Pointers"],
  "977": ["Array", "Two Pointers", "Sorting"],
  "994": ["Array", "Breadth-First Search", "Matrix"],
  "1143": ["String", "Dynamic Programming"],
};

export const KEYWORD_TOPICS: Record<string, string> = {
  "tree": "Tree",
  "binary tree": "Tree",
  "bst": "Tree",
  "linked list": "Linked List",
  "array": "Array",
  "string": "String",
  "dp": "Dynamic Programming",
  "dynamic programming": "Dynamic Programming",
  "graph": "Graph",
  "matrix": "Matrix",
  "backtracking": "Backtracking",
  "sliding window": "Sliding Window",
  "binary search": "Binary Search",
  "stack": "Stack",
  "queue": "Queue",
  "heap": "Heap (Priority Queue)",
  "priority queue": "Heap (Priority Queue)",
  "greedy": "Greedy",
  "trie": "Trie",
  "union find": "Union Find",
  "hash": "Hash Table",
  "map": "Hash Table",
  "set": "Hash Table",
  "sort": "Sorting",
  "bitwise": "Bit Manipulation",
  "two pointers": "Two Pointers",
  "palindrome": "String",
  "anagram": "String",
  "dfs": "Depth-First Search",
  "depth-first search": "Depth-First Search",
  "bfs": "Breadth-First Search",
  "breadth-first search": "Breadth-First Search",
  "prefix sum": "Prefix Sum",
};

export function getTopics(id: string, title: string): string[] {
  if (TOPIC_MAPPING[id]) {
    return TOPIC_MAPPING[id];
  }

  const foundTopics = new Set<string>();
  const lowerTitle = title.toLowerCase();

  for (const [keyword, topic] of Object.entries(KEYWORD_TOPICS)) {
    if (lowerTitle.includes(keyword)) {
      foundTopics.add(topic);
    }
  }

  return foundTopics.size > 0 ? Array.from(foundTopics) : ["Miscellaneous"];
}
